services:
  mongo:
    image: mongo:7
    container_name: nest-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - nest-net
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  redis:
    image: redis/redis-stack-server:latest
    container_name: nest-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - nest-net
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  ingest-service:
    build:
      context: .
      dockerfile: apps/ingest-service/Dockerfile
    container_name: nest-ingest-service
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      INGEST_PORT: 3001
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB_INGEST: nest_ingest
      REDIS_URL: redis://redis:6379
      EVENT_STREAM_KEY: stream:ingest:actions
    ports:
      - '3001:3001'
    volumes:
      - ./apps/ingest-service/storage:/app/apps/ingest-service/storage
      - ./apps/ingest-service/uploads:/app/apps/ingest-service/uploads
    networks:
      - nest-net
    restart: unless-stopped

  audit-service:
    build:
      context: .
      dockerfile: apps/audit-service/Dockerfile
    container_name: nest-audit-service
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
      ingest-service:
        condition: service_started
    environment:
      AUDIT_PORT: 3002
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB_AUDIT: nest_audit
      REDIS_URL: redis://redis:6379
      EVENT_STREAM_KEY: stream:ingest:actions
      EVENT_GROUP: audit-consumers
      EVENT_CONSUMER: audit-1
    ports:
      - '3002:3002'
    networks:
      - nest-net
    restart: unless-stopped

volumes:
  mongo_data:
  redis_data:

networks:
  nest-net:
    driver: bridge
